import darkLogo from "../assets/dark_logo_2.webp"
import peersConn from "../assets/peer_conn.webp"
import peers from "../assets/peers.webp"
import community from "../assets/community.webp"
import pearBanner from "../assets/pear_banner.webp"
import gearBanner from "../assets/gear_banner.webp"
import gearVerticalVine from "../assets/gear_vertical_vine.webp"
import pearVerticalVine from "../assets/pear_vertical_vine.webp"
import facebook from "../assets/facebook.webp";
import instagram from "../assets/instagram.webp";
import github from "../assets/github.webp";
import twitter from "../assets/twitter.webp";
import uginePic from "../assets/ugine_pic.webp"
import breePic from "../assets/bree_pic.webp"
import brianPic from "../assets/brian_pic.webp"
import charlesPic from "../assets/charles_pic.webp"
import muyaPic from "../assets/muya_pic.webp"
import katsPic from "../assets/kats_pic.webp"
import stevePic from "../assets/steve_pic.webp"
import georgePic from "../assets/george_pic.webp"
import muthiePic from "../assets/muthie_pic.webp"
import jamesPic from "../assets/james_pic.webp"
import melvinMuyaPic from "../assets/melvinMuya_pic.webp"
import brianMuhiaPic from "../assets/BrianMuhia_pic.webp"
import martkingStevePic from "../assets/martkingSteve_pic.webp"
import factoryImage from "../assets/factory_image.webp"
import ideaImage from "../assets/ideas.webp"
import startupImage from "../assets/startup_image.webp"
import camshareIcon from "../assets/camshare_icon.webp"

export {camshareIcon,gearBanner,breePic,brianMuhiaPic,startupImage,ideaImage,factoryImage,martkingStevePic,melvinMuyaPic,jamesPic,muthiePic,georgePic,stevePic,katsPic,muyaPic,charlesPic,brianPic,uginePic,facebook,instagram,twitter,github,gearVerticalVine,pearVerticalVine,pearBanner,community,peers,peersConn,darkLogo}